version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  build:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Run build
workflows:
  version: 2
  main:
    jobs:
      - build
